options:
  formatter:                    stylish
files:
  include:                      'app/javascript/stylesheets/**/*.s+(a|c)ss'
rules:
  # Extends
  extends-before-mixins:        1
  extends-before-declarations:  1
  placeholder-in-extend:        0

  # Mixins
  mixins-before-declarations:   0

  # Line Spacing
  one-declaration-per-line:     1
  empty-line-between-blocks:    1
  single-line-per-selector:     1

  # Disallows
  no-color-keywords:            1
  no-color-literals:            0
  no-css-comments:              0
  no-debug:                     1
  no-duplicate-properties:      2
  no-empty-rulesets:            2
  no-extends:                   0
  no-ids:                       0
  no-important:                 2
  no-invalid-hex:               2
  no-mergeable-selectors:       1
  no-misspelled-properties:     2
  no-qualifying-elements:       0
  no-trailing-zero:             2
  no-transition-all:            0
  no-url-domains:               0
  no-url-protocols:             0
  no-vendor-prefixes:           0
  no-warn:                      1

  # Nesting
  force-attribute-nesting:      0
  force-element-nesting:        0
  force-pseudo-nesting:         0

  # Name Formats
  function-name-format:         1
  mixin-name-format:            1
  placeholder-name-format:      1
  variable-name-format:
    - 1
    -
      allow-leading-underscore: false

  # Style Guide
  border-zero:                  1
  brace-style:                  1
  class-name-format:
    - 2
    -
      convention: hyphenatedbem
  clean-import-paths:           1
  empty-args:                   1
  hex-length:                   1
  hex-notation:                 1
  indentation:                  1
  leading-zero:                 1
  nesting-depth:
    - 1
    -
      max-depth:                3
  property-sort-order:          1
  quotes:                       1
  shorthand-values:             1
  url-quotes:                   1
  variable-for-property:        0
  zero-unit:                    2

  # Inner Spacing
  space-after-comma:            1
  space-before-colon:           1
  space-after-colon:            1
  space-before-brace:           1
  space-before-bang:            1
  space-after-bang:             1
  space-between-parens:         1

  # Final Items
  trailing-semicolon:           2
  final-newline:                1
